# Generated by Django 3.2.13 on 2022-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ニックネーム'),
        ),
    ]
